### PR TITLE
Fix : Write js script to remove automatically generated folders in the node-mongo CLI during development #42

### LINKED ISSUE #42: Write js script to remove automatically generated folders in the node-mongo CLI during development
#### Suggested improvement
During development i.e. while fixing issues or adding features to the [node-mongo CLI codebase](https://github.com/code-collabo/node-mongo-cli), you would definitely need to run the node-mongo command at one point or the other. This will Automatically generate folder(s). 

#### Describe issue associated with the absence of this improvement
- Manually looking for and deleting those folders generated is tedious, especially if you created so many.
- Contributors could push the generated folders to github by mistake.

#### Steps to reproduce issue associated with the absence of this improvement
1. Go to the [node-mongo CLI codebase](https://github.com/code-collabo/node-mongo-cli)
2. Follow the instructions in the [node-mongo contributor guide](https://code-collabo.gitbook.io/node-mongo-v2.3.0/contribution-guide/node-mongo) to install and set up the CLI on your computer in preparation for development
3. Run the `node-mongo` command or follow the [CLI usage](https://code-collabo.gitbook.io/node-mongo-v2.3.0/#cli-usage) instructions in the doc to generate as many folders you like
4. Try looking for all the folders you generated and try to delete them all

#### Improvement details
- Create a file called **cleanup.js** in the root of the CLI repo.
- Write a script inside this file that deletes the automatically generated folders by the CLI (only).
- Add it to the script section of the package.json file. So that when you run **npm run cleanup** the cleanup script is executed.

#### Screenshot (example)
None

#### Modifications
None

#### Additional context
None

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] **cleanup.js** file exists in the root of the CLI repo containing scripts that deletes the automatically generated folders by the CLI (only)
- [ ] Running **npm run cleanup** executes the code inside of the cleanup file
- [ ] I certify that I ran my checklist

### PR DESCRIPTION
**Pull request by oyenuga17**
**This pull request makes the following changes:**
* Fixes code-collabo/node-mongo#42

**General checklist**
- [x] File or folder now contains changes as specified in the issue i worked on
- [x] I have linked the issue I worked on to this pull request submitted by me

**Testing checklist**

Replace this text with the testing checklist from the issue this pull request fixes.

Ping @code-collabo/node-mongo-cli

### CODE REVIEW

**Comment by oyenuga17** [comment]
@Ifycode please review

**Comment by Ifycode** [comment]
Thank you @oyenuga17 
Reviewing this week once our community starts rolling again.
Expect my feedback soon.

**Comment by Ifycode** [comment]
I've reviewed this @oyenuga17 
It doesn't work.
I will merge yours into a PR where I have fixed the changes, then you'll be able to see the solution/correction I cam up with.
Nice attempt though.

**Comment by Ifycode** [comment]
@all-contributors add @oyenuga17 for code

**Pull request merged**
