### PR TITLE
Added and configured .prettierrc.json and .prettierignore file

### PR DESCRIPTION
**Pull request by chuddyjoachim**
prettier configuration

### CODE REVIEW

**Comment by Ifycode** [comment]
Hi @chuddyjoachim. Thanks for your time and contribution. Taking a look at the PR. Looks like the configuration you added is based on personal preference?

Let's discuss this. I have the following comments to make. See them below.

**Review by Ifycode — COMMENTED** [review]
**About semicolons:**

The prettier settings you added removes all semicolons at the end of the statement - code is harder to read this way (for some of us developers. I am an example of such developers. Please consider us). So I wouldn't recommend removing them, so that no excess time is spent looking for the end of a statement.

**Comment by Ifycode** [comment]
**About tab width**
There's settings for this in the [.editorconfig file](https://github.com/code-collabo/node-mongo-cli/blob/develop/.editorconfig). The `tab width` defaults to the `indent size` number and doesn't need to be specified. The project therefore already adopts tab width of 2. See [the doc](https://editorconfig.org/).

**About config file to be used:**
Since the `prettier config` does same thing as the already present `editor config`, I'm wondering if having 2 of such configs in the same project is advisable. 

Is there something prettier brings to the table that editor config doesn't?

**Comment by Ifycode** [comment]
**About single quotes**
Thank you for this. You just opened my eyes to the fact that I only did this for .ts files In the .editorconfig file. We may just need to get .js files to also respond to this there in the . editorconfig file. But let's finish discussing what to do with the config files as explained in my previous comment, to know what step to take.

**Comment by Ifycode** [comment]
````
{
    "trailingComma": "es5",
    "useTabs": false
}
````

I'm yet to understand what these do. I've tried browsing, but no meaningful result. Mind helping me with explanation or resource to help me understand?

**Comment by chuddyjoachim** [comment]
@Ifycode 

 **About single quotes**
 Despite adding `.editorconfig`, Most `IDE'S` overrides it and changes single quote to double quote
 since most of the codes had single quotes, I didn't want my commits to affect the projects

**Comment by Ifycode** [comment]
I understand [what you've noted](https://github.com/code-collabo/node-mongo-cli/pull/78#issuecomment-841715126) which is why I didn't attempt to close the PR in the 1st place, and trying to suggest and discuss a workaround... 

I also didn't get a reply from you concerning [the question I asked above](https://github.com/code-collabo/node-mongo-cli/pull/78#issuecomment-841699939).

At least let the conversation be completed and both parties agree that a PR is no more needed, before you close a PR? I would prefer this.

Let me know if you are willing to try out the suggestions I have.

**Comment by Ifycode** [comment]
@chuddyjoachim I understand [what you've noted](https://github.com/code-collabo/node-mongo-cli/pull/78#issuecomment-841715126) which is why I didn't attempt to close the PR in the 1st place, and trying to suggest and discuss a workaround... 

I also didn't get a reply from you concerning [the question I asked above](https://github.com/code-collabo/node-mongo-cli/pull/78#issuecomment-841699939).

At least let the conversation be completed and both parties agree that a PR is no more needed, before you close a PR? I would prefer this.

Let me know if you are willing to try out the suggestions I have.

**Pull request closed without merging**
